### ISSUE TITLE
Keyboard does not render correctly in rtl mode

### ISSUE THREAD

**Issue by meblum** [hodgef/simple-keyboard#1090] opened 2021-06-13 21:59 UTC
latest version

**Describe the bug**
When document is set `dir="rtl`, keyboard buttons on the left side are loose their space.  [sandbox example](https://codesandbox.io/s/laughing-black-cc6mv?file=/index.html) 

![Screenshot 2021-06-13 175931](https://user-images.githubusercontent.com/33358938/121823119-25a6ef00-cc71-11eb-8dd3-d2d3799013ea.png)

**Comment by hodgef** [comment] 2021-06-13 22:27
Duplicate of #803

**Closed by hodgef** 2021-06-13 22:27 UTC
