### ISSUE TITLE
Keyboard fails to init correctly if attached input has a value

### ISSUE THREAD

**Issue by daniel-uribe-sperantus** [hodgef/simple-keyboard#1746] opened 2022-10-14 19:17 UTC
**Simple-keyboard version**
3.4.120

**Describe the bug**
This only happens with the first input with data that activates simple-keyboard on any page. The issue can be reproduced in your code sandbox https://codesandbox.io/s/github/hodgef/vue-simple-keyboard/tree/dark-theme

In the App.vue file, change the initial data 
`data: () => ({
    input: "Some data",
    theme: "hg-theme-default myTheme1"
  }),`

Then click on the input and try for example deleting with backspace, it won't do anything, even if you click multiple times.
If you click any letter or number, it will clear the whole input data, even when the cursor appears to be at the end of the string, and then it will start behaving normally

**Comment by hodgef** [comment] 2022-10-15 01:28
Duplicate of #55

**Closed by hodgef** 2022-10-15 01:28 UTC
