### ISSUE TITLE
Input position uchanged

### ISSUE THREAD

**Issue by chetrix** [hodgef/simple-keyboard#810] opened 2020-11-18 16:36 UTC
Hi,
 I have been facing an issue. Given the scenario-
I have an input field of width 18vw. My input field is incorporated with react simple keyboard. Text is not moving after input field is filled.I have to scroll to the length of the text field to type again. Please help

**Comment by hodgef** [comment] 2020-11-18 17:17
Duplicate of #80

**Closed by hodgef** 2020-11-18 17:17 UTC
Labels: 👥 Duplicate, 📦 Use case

**Comment by chetrix** [comment] 2020-11-18 18:11
Thanks. it worked !!!
