### ISSUE TITLE
Backspace not working when input field has a default value

### ISSUE THREAD

**Issue by Ardyey** [hodgef/simple-keyboard#858] opened 2021-01-05 03:15 UTC
**Simple-keyboard version**
simple-keyboard v2.32.71

**Describe the bug**
As the title says, when there's a default value for the input field where the keyboard listens to, backspace is not working. 
This is taken using the following demo:
https://hodgef.com/simple-keyboard/editor/?d=hodgef/simple-keyboard-js-demos

**GIF**
![Bug](https://user-images.githubusercontent.com/35645526/103602542-4000d200-4f47-11eb-8c2c-7899d1f0c4b3.gif)

**Comment by Ardyey** [comment] 2021-01-05 03:36
Quick Fix: Check if the input field has a default value, if there is, then set the keyboard input value using `keyboard.setInput(value)`

Example:

```
let el = document.querySelector('#name').value;

if (el || el.trim.length > 0) {
 keyboard.setInput(el);
}
```

**Comment by hodgef** [comment] 2021-01-05 04:51
Hello @Ardyey ,

You've got it right: if an input has a default value, this needs to be synced with simple-keyboard through [`keyboard.setInput()`](https://hodgef.com/simple-keyboard/documentation/methods/setinput/) or [`keyboard.replaceInput()`](https://hodgef.com/simple-keyboard/documentation/methods/replaceinput/).

Closing as duplicate of https://github.com/hodgef/simple-keyboard/issues/55#issuecomment-466401011

Thanks!
Francisco Hodge

**Closed by hodgef** 2021-01-05 04:51 UTC
Labels: 📦 Use case
