### ISSUE TITLE
ReferenceError: window is not defined

### ISSUE THREAD

**Issue by alejandroclaro** [hodgef/simple-keyboard#557] opened 2020-05-13 18:21 UTC
**Simple-keyboard version**
Version: 2.29.17

**Describe the bug**
When the simple keyboard is included in a Vue.js component written in typescript and used in an electron application if the package is imported, the following error occurs at runtime:

> ReferenceError: window is not defined

A similar issue was reported in #476. The workaround mentioned in this ticket is not a complete solution. When dynamic import, or `require` directly, is used when the Vue.js (or React) component is mounted, the typescript declaration symbols are not recognized at a file level. We had to copy and paste part of the declaration file (.d.ts) into a shim file to make it work.

It seems that the problems have to do with the package format (UMD). This can only be imported once the 'window' variable has been defined. It would be nice if an ES6 module bundle can be also be generated and distributed to solve this problem and avoid workarounds.

**Comment by hodgef** [comment] 2020-05-13 18:41
Hello @alejandroclaro,

I don't think you'll see this error in the renderer of an electron application. I think you're probably using SSR where window is not defined.

Regarding out of the box SSR support without conditional imports, please check out my response to your first comment here: 

https://github.com/hodgef/simple-keyboard/issues/476#issuecomment-628173273

I'll close this as a dupe of #520 

Regards,
Francisco Hodge

**Closed by hodgef** 2020-05-13 18:41 UTC
Labels: 👥 Duplicate

**Comment by alejandroclaro** [comment] 2020-05-15 11:32
@hodgef Please don't close this issue. This is a real issue and not the same cause in #520.

We are not using any SSR. We are loading the Vue component in a renderer process in a electron application. The window is eventually defined, but not at the moment the modules are imported.

We have a traditional electron setup:

``` html
<body>
  <div id="app">
  </div>
  <script src="index.cjs.js">
  </script>
</body>
```

and the Vue.js component that wraps 'simple-keyboard' is imported in the 'index.cjs.js' script that is loaded in the HTML. If we import simple-keyboard in the '.vue' in the traditional way:

``` typescript
import SimpleKeyboard from 'simple-keyboard';

export default class MyComponent extends Vue {
 // ...
}
```
 We get this `window is not defined` error. If we use dynamic import or 'require' in the `mounted` hook or just after the class is instantiated:

``` typescript
export default class MyComponent extends Vue {
  private SimpleKeyboard = require('simple-keyboard').default;

  protected mounted(): void {
    const divElement = this.$refs.keyboard as HTMLDivElement;
    this.keyboard = new this.SimpleKeyboard(divElement, {
       // ...
    });
  }
}
```

everything works, but we don't have the type information and we are forced to create a shim for the types:

``` typescript
// shims-simple-keyboard.d.ts
declare module 'simple-keyboard'{
  export interface SimpleKeyboard{
    setInput: Function;
    setOptions: Function;
  }
}
```

And this should be no necessary. The problem looks like something to be with the UMD bundle structure.

**Comment by hodgef** [comment] 2020-05-15 17:42
Could you provide a repro for this? I cannot reproduce this on a Vue Electron application.

![image](https://user-images.githubusercontent.com/25509135/82079852-8d2aed80-96b1-11ea-987d-8566a8522b23.png)

It seems to work with the same code as the basic Vue demo (without conditional imports): 

https://codesandbox.io/s/github/hodgef/vue-simple-keyboard/tree/master/?from-embed=&file=/src/App.vue:286-332

**Comment by alejandroclaro** [comment] 2020-05-19 12:21
Hi @hodgef we found the problem, but I still think simple-keyboard should not be accessing the window variable during the import.

The problem is that we have a package that needs to export a function to set-up a IPC communication between the main and renderer process. This package also has a Vue.js component that is only imported from the renderer process. What is happening, is that when we import the function from the main process, simple-keyboards import is executing code that depends on window variable even if no UI component is being imported. My guess is that it's trying to register simple-keyboard type as a global in window.

**Comment by hodgef** [comment] 2020-05-19 14:32
My understanding is that an import should not trigger a `window` error, since the constructor is not yet called. Only when you try to instantiate the Keyboard (`new Keyboard(...)`) should it fail, since it requires a browser to be usable.

The conditional import was added in SSR demos since it wouldn't make sense to import an UI component if it's not going to be instantiated. But having a static import by itself should not cause errors.

Here's an example of an SSR site (Gatsby) importing simple-keyboard (yet not instantiating it) without errors :

![image](https://user-images.githubusercontent.com/25509135/82336628-d41e2900-99b8-11ea-84d1-e0e575653b21.png)
https://codesandbox.io/s/cranky-glitter-9kxpb?file=/src/pages/index.js

That being said, I would like to make the library runnable for SSR users without the need for `if(window){ ... }`. I am tracking this Enhancement in #520. Hopefully I'll get to release an update for it soon.

Regards,
Francisco Hodge

**Comment by alejandroclaro** [comment] 2020-05-20 09:30
Thanks @hodgef 

I will try to find some time to publish a repository with the bug to provide a playground for this. We are still struggling with this and the workaround is pretty ugly. We had to create a shim and introduce 'require(/simple-keyboard').default' inside the class to be able to get rid of the error.
