### ISSUE TITLE
Touch down makes input loose focus

### ISSUE THREAD

**Issue by maxfahl** [hodgef/simple-keyboard#79] opened 2019-05-22 09:27 UTC
**Simple-keyboard version**
2.21.0

**Describe the bug**
When using the preventMouseDownDefault property together with useTouchEvents, the input field looses focus when typing on the keyboard. I've attached listeners for focus and blur on my input to toggle visibility of the keyboard. Whenever the textfield looses focus the keyboard hides. It works as expected works correctly with mouse events.

**Comment by hodgef** [comment] 2019-05-22 21:11
Hello @maxfahl,

I was not able to reproduce the issue on Chrome emulator nor on an Android tablet.  [Here's the sandbox I used to debug.](https://codesandbox.io/s/simplekeyboardnpmdemos-pjek0)

However, I did notice the input losing focus when tapping *between* the keys (on Android). Could you confirm if this is the issue you're experiencing?


Also, if you could provide a bit more specifics it would help nail down the issue. eg.: The framework you're using (Angular, Vue, if any.), OS, etc.

I will close the issue for now and reopen as I get this info.

Thanks,
Francisco hodge

**Closed by hodgef** 2019-05-22 21:11 UTC
Labels: 🔍 Investigating
