### ISSUE TITLE
React Keyboard Key Size

### ISSUE THREAD

**Issue by SaMs-Hub** [hodgef/simple-keyboard#1362] opened 2021-12-07 12:15 UTC
**Is your feature request related to a problem? Please describe.**
Problem with using the React version of the Keyboard, Want to change the size of specific keys

**Describe the solution you'd like**
Being able to change the size of keys provided.

- Current usage of the keyboard

![KeyboardSize](https://user-images.githubusercontent.com/76864645/145026673-27a35d1c-98b4-455a-87d0-dc82059e3703.jpg)

- Expected key size manipulation like

 ![ExpectedKeyboard](https://user-images.githubusercontent.com/76864645/145027159-fb700331-61ac-44a5-b5f2-77d8e1f81dc3.jpg)

**Comment by hodgef** [comment] 2021-12-07 22:57
Duplicate of https://github.com/hodgef/react-simple-keyboard/issues/1660

**Closed** 2021-12-07 22:57 UTC
Labels: 👥 Duplicate
