### ISSUE TITLE
If keyboard already has input value. Backspace key doesn't work and keyboard entirely starts new input on pressing any key.

### ISSUE THREAD

**Issue by anehal123** [hodgef/simple-keyboard#1634] opened 2022-07-18 13:32 UTC
I am using below code to set the value when user gives any input from onscreen kbd.

 public onChange = (input: string) => {
  this.data.content.inputValue = input;
  }

**Comment by hodgef** [comment] 2022-07-20 20:07
Duplicate of #55

**Comment by hodgef** [comment] 2022-07-20 20:07
More info: https://github.com/hodgef/simple-keyboard/issues/858#issuecomment-754394081

**Closed by hodgef** 2022-07-20 20:07 UTC
Labels: 📦 Use case
